---
title: "Experience"
---

## Toxicology of Cyanobacteria in Lake Winniepesaukee
I worked under the Center for Freshwater Biology, investigating harmful cyanobacterial blooms across Lake Winnipesaukee and neighboring lakes to assess ecological and public health impact. I identified key cyanobacterial taxa influencing ecosystem health.   

## New Zealand Research: Invertebrate Sampling on Lake Waikare 
While in New Zealand, I conducted a 6-week intensive research project in the Waikato Region, collecting and analyzing data on 15,955 invertebrates (795 species) and presented findings to stakeholders. We used invertebrates as bioindicators to assess the role native vegetation had in restoring ecosystem function to an area that was very depleted in nutrients. 

## Lakes Lays Monitoring Program
During my summer internship in 2025, I conducted pH/conductivity, chloride, turbidity, alkalinity, CO2, fluorometry, color and chlorophyll, and phosphorous tests in the lab in order to assess the quality of over 30 lakes in New Hampshire. I also worked alongside volunteers and helped to educate them as well as the general public about the importance of water quality and how to conduct these tests on their own lakes. 

## Loon Preservation Committee
During my summer internship in 2024, I was the Lake Winnipesaukee Loon Field Biologist. I collected behavioral and population data on loons through daily field surveys. I also assisted in loon captures, banding, and recovery of injured or deceased individuals for further investigation. 

## Quantitative Marine Ecology Lab
In this lab, myself along with a peer, researched trophic interactions among temperate reef fish populations in Californian kelp forests. We presented at the Undergraduate Research Conference at the University of New Hampshire in April 2024.

## Ecological and Acoustics Behavior Lab
While working in this research lab, I, along with two of my peers, studied how the frequency of gate bangs from the giraffes correlated with the passing of a nearby train. We looked at how giraffes gate bangs represented their stress and prepared a summary paper to give to their team. In the spring, I researched and evaluated the frequencies of calls that cows, bulls, and calves made and what those calls could tell us about their behavior (were they rutting, communicating, warning calls, etc.). Myself along with two peers presented at Northeast Regional Environmental Acoustics Symposium as well as the URC at UNH in April 2023.

DOI for paper: 10.1121/10.0025465

